// react-based-lading-page/src/components/landing/Footer.tsx
import { useState } from "react";
import { motion } from "framer-motion";
import { Github, Twitter, Linkedin, Mail, ArrowRight } from "lucide-react";
import { Input } from "@/components/ui/input";
import { GlowButton } from "./shared/GlowButton";
import { fadeUp, staggerContainer } from "@/lib/animations";

const footerLinks = {
  product: [
    { label: "Services", href: "#services" },
    { label: "Process", href: "#process" },
    { label: "Pricing", href: "#pricing" },
    { label: "FAQ", href: "#faq" },
  ],
  company: [
    { label: "About", href: "#" },
    { label: "Careers", href: "#" },
    { label: "Blog", href: "#" },
    { label: "Contact", href: "#" },
  ],
  legal: [
    { label: "Privacy", href: "#" },
    { label: "Terms", href: "#" },
    { label: "Cookies", href: "#" },
  ],
};

const socialLinks = [
  { icon: Twitter, href: "#", label: "Twitter" },
  { icon: Github, href: "#", label: "GitHub" },
  { icon: Linkedin, href: "#", label: "LinkedIn" },
  { icon: Mail, href: "mailto:hello@devforge.io", label: "Email" },
];

export function Footer() {
  const [email, setEmail] = useState("");

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    // Handle newsletter signup
    console.log("Newsletter signup:", email);
    setEmail("");
  };

  return (
    <footer className="border-t border-slate-800">
      <motion.div
        initial="hidden"
        whileInView="visible"
        viewport={{ once: true }}
        variants={staggerContainer}
        className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16"
      >
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 lg:gap-24 mb-12">
          {/* Newsletter section */}
          <motion.div variants={fadeUp}>
            <h3 className="text-2xl font-bold text-white mb-2">
              Stay in the loop
            </h3>
            <p className="text-slate-400 mb-6">
              Get product updates, company news, and startup insights delivered
              to your inbox.
            </p>
            <form onSubmit={handleSubmit} className="flex gap-3">
              <Input
                type="email"
                placeholder="Enter your email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                className="flex-1"
                required
              />
              <GlowButton type="submit">
                Subscribe
                <ArrowRight className="ml-2 w-4 h-4" />
              </GlowButton>
            </form>
          </motion.div>

          {/* Links section */}
          <motion.div
            variants={fadeUp}
            className="grid grid-cols-3 gap-8"
          >
            <div>
              <h4 className="text-sm font-semibold text-white uppercase tracking-wider mb-4">
                Product
              </h4>
              <ul className="space-y-3">
                {footerLinks.product.map((link) => (
                  <li key={link.label}>
                    <a
                      href={link.href}
                      className="text-sm text-slate-400 hover:text-white transition-colors"
                    >
                      {link.label}
                    </a>
                  </li>
                ))}
              </ul>
            </div>
            <div>
              <h4 className="text-sm font-semibold text-white uppercase tracking-wider mb-4">
                Company
              </h4>
              <ul className="space-y-3">
                {footerLinks.company.map((link) => (
                  <li key={link.label}>
                    <a
                      href={link.href}
                      className="text-sm text-slate-400 hover:text-white transition-colors"
                    >
                      {link.label}
                    </a>
                  </li>
                ))}
              </ul>
            </div>
            <div>
              <h4 className="text-sm font-semibold text-white uppercase tracking-wider mb-4">
                Legal
              </h4>
              <ul className="space-y-3">
                {footerLinks.legal.map((link) => (
                  <li key={link.label}>
                    <a
                      href={link.href}
                      className="text-sm text-slate-400 hover:text-white transition-colors"
                    >
                      {link.label}
                    </a>
                  </li>
                ))}
              </ul>
            </div>
          </motion.div>
        </div>

        {/* Bottom section */}
        <motion.div
          variants={fadeUp}
          className="flex flex-col sm:flex-row items-center justify-between pt-8 border-t border-slate-800 gap-4"
        >
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-indigo-500 to-purple-600 flex items-center justify-center">
              <span className="text-white font-bold text-sm">D</span>
            </div>
            <span className="text-sm text-slate-400">
              &copy; {new Date().getFullYear()} DevForge. All rights reserved.
            </span>
          </div>

          <div className="flex items-center gap-4">
            {socialLinks.map((social) => (
              <a
                key={social.label}
                href={social.href}
                className="w-10 h-10 rounded-lg bg-slate-800/50 flex items-center justify-center text-slate-400 hover:text-white hover:bg-slate-800 transition-colors"
                aria-label={social.label}
              >
                <social.icon className="w-5 h-5" />
              </a>
            ))}
          </div>
        </motion.div>
      </motion.div>
    </footer>
  );
}

// angular-based-landing-page/src/app/components/footer/footer.component.ts
import { Component, signal, ChangeDetectionStrategy } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { LucideAngularModule, ArrowRight, Instagram, Twitter, Youtube } from 'lucide-angular';
import { ScrollRevealDirective } from '../../directives/scroll-reveal.directive';

@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [FormsModule, LucideAngularModule, ScrollRevealDirective],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <footer class="relative pt-32 pb-12">
      <div class="absolute top-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-white/10 to-transparent"></div>

      <div class="max-w-7xl mx-auto px-6">
        <!-- Newsletter -->
        <div class="text-center mb-24" appScrollReveal>
          <p class="text-xs tracking-mega uppercase text-amber-500/80 font-light mb-4">Newsletter for the Elite</p>
          <h2 class="text-3xl sm:text-4xl font-extralight tracking-tight mb-4">Stay Ahead of the Curve</h2>
          <p class="text-zinc-500 text-sm font-light max-w-md mx-auto mb-8">
            Exclusive previews, first access to new arrivals, and invitations to private events.
          </p>

          <div class="flex flex-col sm:flex-row items-center gap-3 max-w-md mx-auto">
            <input
              [(ngModel)]="email"
              type="email"
              placeholder="your@email.com"
              class="flex-1 w-full bg-white/5 border border-white/10 px-5 py-3.5 text-sm font-light text-white placeholder:text-zinc-600 focus:outline-none focus:border-amber-500/40 transition-colors"
            />
            <button
              (click)="subscribed.set(true)"
              class="w-full sm:w-auto flex items-center justify-center gap-2 px-6 py-3.5 bg-white text-zinc-950 text-xs tracking-widest uppercase font-medium hover:bg-amber-500 transition-all duration-300 whitespace-nowrap"
            >
              @if (subscribed()) {
                Subscribed
              } @else {
                Subscribe
                <lucide-icon [img]="arrowRight" [size]="14"></lucide-icon>
              }
            </button>
          </div>
        </div>

        <!-- Footer Grid -->
        <div class="grid grid-cols-2 md:grid-cols-4 gap-10 mb-16" [appScrollReveal]="100">
          @for (col of footerColumns; track col.title) {
            <div>
              <h4 class="text-[10px] tracking-mega uppercase text-zinc-500 mb-5">{{ col.title }}</h4>
              <ul class="space-y-3">
                @for (link of col.links; track link) {
                  <li>
                    <a href="#" class="text-sm font-light text-zinc-400 hover:text-white transition-colors duration-300">
                      {{ link }}
                    </a>
                  </li>
                }
              </ul>
            </div>
          }
        </div>

        <!-- Bottom Bar -->
        <div class="flex flex-col sm:flex-row items-center justify-between pt-8 border-t border-white/5 gap-6">
          <!-- Logo -->
          <div class="flex items-center gap-3">
            <div class="w-6 h-6 border border-amber-500/40 rotate-45 flex items-center justify-center">
              <div class="w-1.5 h-1.5 bg-amber-500 rotate-[-45deg]"></div>
            </div>
            <span class="text-xs font-light tracking-ultra uppercase text-zinc-500">Apex Velocity</span>
          </div>

          <!-- Social -->
          <div class="flex items-center gap-5">
            @for (social of socials; track social.label) {
              <a href="#" class="text-zinc-600 hover:text-white transition-colors duration-300" [attr.aria-label]="social.label">
                <lucide-icon [img]="social.icon" [size]="16"></lucide-icon>
              </a>
            }
          </div>

          <!-- Copyright -->
          <p class="text-[10px] tracking-widest uppercase text-zinc-600">
            &copy; 2025 Apex Velocity. All rights reserved.
          </p>
        </div>
      </div>
    </footer>
  `,
})
export class FooterComponent {
  readonly arrowRight = ArrowRight;

  email = '';
  subscribed = signal(false);

  socials = [
    { icon: Instagram, label: 'Instagram' },
    { icon: Twitter, label: 'Twitter' },
    { icon: Youtube, label: 'YouTube' },
  ];

  footerColumns = [
    {
      title: 'Showroom',
      links: ['Current Inventory', 'Coming Soon', 'Sold Archive', 'Request a Build'],
    },
    {
      title: 'Services',
      links: ['Financing', 'Trade-In', 'Transport', 'Concierge'],
    },
    {
      title: 'Company',
      links: ['About Us', 'Careers', 'Press', 'Contact'],
    },
    {
      title: 'Legal',
      links: ['Privacy Policy', 'Terms of Service', 'Cookie Policy', 'Accessibility'],
    },
  ];
}
