// angular-based-landing-page/src/app/components/hero/hero.component.ts
import { Component, ChangeDetectionStrategy } from '@angular/core';
import { LucideAngularModule, ArrowRight, Play } from 'lucide-angular';

@Component({
  selector: 'app-hero',
  standalone: true,
  imports: [LucideAngularModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section class="relative h-screen flex items-center justify-center overflow-hidden">
      <!-- Background Image with Overlay -->
      <div class="absolute inset-0">
        <img
          src="https://images.unsplash.com/photo-1544636331-e26879cd4d9b?auto=format&fit=crop&w=2000&q=80"
          alt="Luxury sports car"
          class="w-full h-full object-cover"
        />
        <div class="absolute inset-0 bg-gradient-to-b from-zinc-950/70 via-zinc-950/50 to-zinc-950"></div>
        <div class="absolute inset-0 bg-gradient-to-r from-zinc-950/80 via-transparent to-zinc-950/80"></div>
      </div>

      <!-- Content -->
      <div class="relative z-10 text-center max-w-5xl mx-auto px-6">
        <div class="space-y-8">
          <!-- Overline -->
          <p class="text-xs tracking-mega uppercase text-amber-500/80 font-light">
            Est. 2024 — Exclusive Automotive
          </p>

          <!-- Headline -->
          <h1 class="text-5xl sm:text-7xl lg:text-8xl font-extralight tracking-tight leading-[0.9]">
            Engineered
            <br />
            <span class="text-gradient font-thin">Emotion</span>
          </h1>

          <!-- Subline -->
          <p class="text-zinc-400 text-lg sm:text-xl font-extralight max-w-2xl mx-auto leading-relaxed">
            Where raw power meets refined elegance. Discover the world's most
            extraordinary machines, curated for the discerning few.
          </p>

          <!-- CTAs -->
          <div class="flex flex-col sm:flex-row items-center justify-center gap-4 pt-4">
            <a
              href="#collection"
              class="group flex items-center gap-3 px-8 py-4 bg-white text-zinc-950 text-sm tracking-widest uppercase font-medium hover:bg-amber-500 transition-all duration-300"
            >
              View Inventory
              <lucide-icon [img]="arrowRight" [size]="16" class="group-hover:translate-x-1 transition-transform"></lucide-icon>
            </a>
            <a
              href="#experience"
              class="group flex items-center gap-3 px-8 py-4 border border-white/20 text-sm tracking-widest uppercase font-light text-zinc-300 hover:border-white/40 hover:text-white transition-all duration-300"
            >
              <lucide-icon [img]="playIcon" [size]="14"></lucide-icon>
              Watch Film
            </a>
          </div>
        </div>
      </div>

      <!-- Scroll Indicator -->
      <div class="absolute bottom-10 left-1/2 -translate-x-1/2 flex flex-col items-center gap-3">
        <span class="text-[10px] tracking-mega uppercase text-zinc-500">Scroll</span>
        <div class="w-px h-12 bg-gradient-to-b from-zinc-500 to-transparent"></div>
      </div>

      <!-- Side Accent Lines -->
      <div class="absolute top-1/2 left-6 -translate-y-1/2 hidden lg:block">
        <div class="w-px h-32 bg-gradient-to-b from-transparent via-amber-500/30 to-transparent"></div>
      </div>
      <div class="absolute top-1/2 right-6 -translate-y-1/2 hidden lg:block">
        <div class="w-px h-32 bg-gradient-to-b from-transparent via-amber-500/30 to-transparent"></div>
      </div>
    </section>
  `,
})
export class HeroComponent {
  readonly arrowRight = ArrowRight;
  readonly playIcon = Play;
}

// next-based-landing-page/src/components/hero.tsx
"use client";

import Image from "next/image";
import { motion } from "framer-motion";
import { ArrowDown } from "lucide-react";

export function Hero() {
  return (
    <section className="relative flex h-screen items-center justify-center overflow-hidden">
      {/* Background Image */}
      <div className="absolute inset-0">
        <Image
          src="https://images.unsplash.com/photo-1618220179428-22790b461013?w=1920&q=80&auto=format&fit=crop"
          alt="White marble interior with soft natural light"
          fill
          priority
          className="object-cover"
          sizes="100vw"
          placeholder="blur"
          blurDataURL="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMCwsKCwsQERIQDg8RERMTEhMSEBEUFRUVFBcYFxcZGhobGhT/2wBDAQMEBAUEBQkFBQkaEA8QGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhr/wAARCAADAAQDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAFBABAAAAAAAAAAAAAAAAAAAABv/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/AKgA/9k="
        />
        <div className="absolute inset-0 bg-white/40" />
      </div>

      {/* Content */}
      <div className="relative z-10 text-center">
        <motion.p
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 1.2, delay: 0.3 }}
          className="mb-6 text-xs tracking-luxury uppercase text-slate-400"
        >
          Curated in white
        </motion.p>
        <motion.h1
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 1, delay: 0.6, ease: [0.25, 0.1, 0.25, 1] }}
          className="font-serif text-5xl font-normal leading-tight text-slate-900 md:text-7xl lg:text-8xl"
        >
          The Absence
          <br />
          of Noise
        </motion.h1>
        <motion.p
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 1, delay: 1.0 }}
          className="mt-8 text-sm tracking-wide text-slate-400"
        >
          An ultra-luxury collection of pure, curated white
        </motion.p>
      </div>

      {/* Scroll Indicator */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 1, delay: 1.5 }}
        className="absolute bottom-10 left-1/2 -translate-x-1/2"
      >
        <motion.div
          animate={{ y: [0, 8, 0] }}
          transition={{ duration: 2, repeat: Infinity, ease: "easeInOut" }}
        >
          <ArrowDown size={18} strokeWidth={1} className="text-slate-400" />
        </motion.div>
      </motion.div>
    </section>
  );
}
